# Generated by Django 6.0.3 on 2026-04-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tecnologia",
            name="nivel",
        ),
        migrations.AddField(
            model_name="docente",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="docentes/"),
        ),
        migrations.AddField(
            model_name="experienciaprofissional",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AddField(
            model_name="formacao",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="ects_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="sigla",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="url_oficial",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="makingof",
            name="entidade_relacionada",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="projeto",
            name="destaque",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="nivel_interesse",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=3
            ),
        ),
        migrations.AddField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AlterField(
            model_name="competencia",
            name="nivel",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], default=3
            ),
        ),
        migrations.AlterField(
            model_name="experienciaprofissional",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio.competencia"),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio.competencia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio.competencia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(blank=True, to="portfolio.docente"),
        ),
    ]
