# Generated by Django 6.0.3 on 2026-04-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_tecnologia_nivel_docente_foto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competencia",
            options={
                "verbose_name": "Competência",
                "verbose_name_plural": "Competências",
            },
        ),
        migrations.AlterModelOptions(
            name="docente",
            options={"verbose_name": "Docente", "verbose_name_plural": "Docentes"},
        ),
        migrations.AlterModelOptions(
            name="experienciaprofissional",
            options={
                "verbose_name": "Experiência Profissional",
                "verbose_name_plural": "Experiências Profissionais",
            },
        ),
        migrations.AlterModelOptions(
            name="formacao",
            options={"verbose_name": "Formação", "verbose_name_plural": "Formações"},
        ),
        migrations.AlterModelOptions(
            name="licenciatura",
            options={
                "verbose_name": "Licenciatura",
                "verbose_name_plural": "Licenciaturas",
            },
        ),
        migrations.AlterModelOptions(
            name="makingof",
            options={"verbose_name": "Making Of", "verbose_name_plural": "Making Of"},
        ),
        migrations.AlterModelOptions(
            name="projeto",
            options={"verbose_name": "Projeto", "verbose_name_plural": "Projetos"},
        ),
        migrations.AlterModelOptions(
            name="tecnologia",
            options={
                "verbose_name": "Tecnologia",
                "verbose_name_plural": "Tecnologias",
            },
        ),
        migrations.AlterModelOptions(
            name="tfc",
            options={"verbose_name": "TFC", "verbose_name_plural": "TFCs"},
        ),
        migrations.AlterModelOptions(
            name="unidadecurricular",
            options={
                "verbose_name": "Unidade Curricular",
                "verbose_name_plural": "Unidades Curriculares",
            },
        ),
    ]
