# Generated by Django 6.0.3 on 2026-04-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_competencia_options_alter_docente_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competencia",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="experienciaprofissional",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.TextField(blank=True),
        ),
    ]
