# Generated by Django 6.0.3 on 2026-04-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_competencia_descricao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("descricao", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Tipo",
                "verbose_name_plural": "Tipos",
                "ordering": ["nome"],
            },
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecnologias",
                to="portfolio.tipo",
            ),
        ),
    ]
